services:

  api:
    build:
      context: ../
    container_name: e_journal_api
    env_file:
      - ../.env
    command: ./infra/commands/api.sh
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: e_journal_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
