services:

  api:
    build:
      context: ../
    container_name: test_e_journal_api
    env_file:
      - ../.env.test
    command: "./infra/commands/test_api.sh"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: test_e_journal_db
    env_file:
      - ../.env.test
    ports:
      - "5433:5432"
